-- Add balance to users
ALTER TABLE users
ADD COLUMN balance DECIMAL(20,8) NOT NULL DEFAULT 100.0;

-- Trades generated by the matching engine
CREATE TABLE trades (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id UUID NOT NULL REFERENCES events(id),
    outcome VARCHAR(10) NOT NULL CHECK (outcome IN ('YES', 'NO')),

    taker_order_id UUID NOT NULL REFERENCES orders(id),
    maker_order_id UUID NOT NULL REFERENCES orders(id),

    buyer_id UUID NOT NULL REFERENCES users(id),
    seller_id UUID NOT NULL REFERENCES users(id),

    taker_side VARCHAR(10) NOT NULL CHECK (taker_side IN ('BUY', 'SELL')),

    quantity DECIMAL(20,8) NOT NULL,
    price DECIMAL(20,8) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- User positions
CREATE TABLE positions (
    user_id UUID NOT NULL REFERENCES users(id),
    event_id UUID NOT NULL REFERENCES events(id),
    outcome VARCHAR(10) NOT NULL CHECK (outcome IN ('YES', 'NO')),

    shares DECIMAL(20,8) NOT NULL DEFAULT 0,
    avg_price DECIMAL(20,8) NOT NULL DEFAULT 0,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (user_id, event_id, outcome)
);

-- Account transactions / ledger
CREATE TABLE transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL REFERENCES users(id),
    order_id UUID REFERENCES orders(id),
    trade_id UUID REFERENCES trades(id),

    type VARCHAR(30) NOT NULL,

    quantity DECIMAL(20,8),
    price DECIMAL(20,8),
    amount DECIMAL(20,8) NOT NULL,

    outcome VARCHAR(10),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_trades_event_id
ON trades(event_id);

CREATE INDEX idx_trades_created_at
ON trades(created_at);

CREATE INDEX idx_positions_user_id
ON positions(user_id);

CREATE INDEX idx_transactions_user_id
ON transactions(user_id);

CREATE INDEX idx_orders_event_status
ON orders(event_id, status);

CREATE INDEX idx_orders_user_event
ON orders(user_id, event_id);