// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (id, title, description, question, thumbnail, expires_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5)
RETURNING id, title, description, question, thumbnail, is_active, expires_at, created_at, updated_at
`

type CreateEventParams struct {
	Title       string
	Description string
	Question    string
	Thumbnail   string
	ExpiresAt   pgtype.Timestamptz
}

type CreateEventRow struct {
	ID          uuid.UUID
	Title       string
	Description string
	Question    string
	Thumbnail   string
	IsActive    pgtype.Bool
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.Description,
		arg.Question,
		arg.Thumbnail,
		arg.ExpiresAt,
	)
	var i CreateEventRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Question,
		&i.Thumbnail,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getActiveEvents = `-- name: GetActiveEvents :many
SELECT id, title, description, question, thumbnail, is_active, expires_at, created_at, updated_at
FROM events
WHERE is_active = true
ORDER BY expires_at ASC
`

type GetActiveEventsRow struct {
	ID          uuid.UUID
	Title       string
	Description string
	Question    string
	Thumbnail   string
	IsActive    pgtype.Bool
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetActiveEvents(ctx context.Context) ([]GetActiveEventsRow, error) {
	rows, err := q.db.Query(ctx, getActiveEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveEventsRow
	for rows.Next() {
		var i GetActiveEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Question,
			&i.Thumbnail,
			&i.IsActive,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, title, description, question, thumbnail, is_active, expires_at, created_at, updated_at
FROM events
WHERE id = $1
`

type GetEventByIDRow struct {
	ID          uuid.UUID
	Title       string
	Description string
	Question    string
	Thumbnail   string
	IsActive    pgtype.Bool
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (GetEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Question,
		&i.Thumbnail,
		&i.IsActive,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, event_id, user_id, order_type, outcome, side, quantity, price, status, filled_quantity, remaining_quantity, created_at, updated_at
FROM orders
WHERE id = $1
`

type GetOrderByIDRow struct {
	ID                uuid.UUID
	EventID           uuid.UUID
	UserID            uuid.UUID
	OrderType         string
	Outcome           string
	Side              string
	Quantity          pgtype.Numeric
	Price             pgtype.Numeric
	Status            string
	FilledQuantity    pgtype.Numeric
	RemainingQuantity pgtype.Numeric
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.OrderType,
		&i.Outcome,
		&i.Side,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.FilledQuantity,
		&i.RemainingQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementEventVolume = `-- name: IncrementEventVolume :exec
UPDATE events
SET volume = volume + $2, updated_at = NOW()
WHERE id = $1
`

type IncrementEventVolumeParams struct {
	ID     uuid.UUID
	Volume pgtype.Numeric
}

func (q *Queries) IncrementEventVolume(ctx context.Context, arg IncrementEventVolumeParams) error {
	_, err := q.db.Exec(ctx, incrementEventVolume, arg.ID, arg.Volume)
	return err
}
