// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOrdersByUserAndEvent = `-- name: GetOrdersByUserAndEvent :many
SELECT id, event_id, user_id, order_type, outcome, side, quantity, price, status, filled_quantity, remaining_quantity, created_at, updated_at
FROM orders
WHERE user_id = $1 AND event_id = $2
`

type GetOrdersByUserAndEventParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

type GetOrdersByUserAndEventRow struct {
	ID                uuid.UUID
	EventID           uuid.UUID
	UserID            uuid.UUID
	OrderType         string
	Outcome           string
	Side              string
	Quantity          pgtype.Numeric
	Price             pgtype.Numeric
	Status            string
	FilledQuantity    pgtype.Numeric
	RemainingQuantity pgtype.Numeric
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetOrdersByUserAndEvent(ctx context.Context, arg GetOrdersByUserAndEventParams) ([]GetOrdersByUserAndEventRow, error) {
	rows, err := q.db.Query(ctx, getOrdersByUserAndEvent, arg.UserID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByUserAndEventRow
	for rows.Next() {
		var i GetOrdersByUserAndEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.OrderType,
			&i.Outcome,
			&i.Side,
			&i.Quantity,
			&i.Price,
			&i.Status,
			&i.FilledQuantity,
			&i.RemainingQuantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO orders (
    id,
    event_id,
    user_id,
    order_type,
    outcome,
    side,
    quantity,
    price,
    status,
    filled_quantity,
    remaining_quantity
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type InsertOrderParams struct {
	ID                uuid.UUID
	EventID           uuid.UUID
	UserID            uuid.UUID
	OrderType         string
	Outcome           string
	Side              string
	Quantity          pgtype.Numeric
	Price             pgtype.Numeric
	Status            string
	FilledQuantity    pgtype.Numeric
	RemainingQuantity pgtype.Numeric
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder,
		arg.ID,
		arg.EventID,
		arg.UserID,
		arg.OrderType,
		arg.Outcome,
		arg.Side,
		arg.Quantity,
		arg.Price,
		arg.Status,
		arg.FilledQuantity,
		arg.RemainingQuantity,
	)
	return err
}

const updateOrderFill = `-- name: UpdateOrderFill :exec
UPDATE orders
SET
    filled_quantity = filled_quantity + $2,
    remaining_quantity = GREATEST(quantity - (filled_quantity + $2), 0),
    status = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateOrderFillParams struct {
	ID             uuid.UUID
	FilledQuantity pgtype.Numeric
	Status         string
}

func (q *Queries) UpdateOrderFill(ctx context.Context, arg UpdateOrderFillParams) error {
	_, err := q.db.Exec(ctx, updateOrderFill, arg.ID, arg.FilledQuantity, arg.Status)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
