// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, event_id, user_id, order_type, outcome, side, quantity, price, status)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, 'PENDING')
RETURNING id, event_id, user_id, order_type, outcome, side, quantity, price, status, created_at, updated_at
`

type CreateOrderParams struct {
	EventID   uuid.UUID
	UserID    uuid.UUID
	OrderType string
	Outcome   string
	Side      string
	Quantity  pgtype.Numeric
	Price     pgtype.Numeric
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.EventID,
		arg.UserID,
		arg.OrderType,
		arg.Outcome,
		arg.Side,
		arg.Quantity,
		arg.Price,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.OrderType,
		&i.Outcome,
		&i.Side,
		&i.Quantity,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersByUserAndEvent = `-- name: GetOrdersByUserAndEvent :many
SELECT id, event_id, user_id, order_type, outcome, side, quantity, price, status, created_at, updated_at
FROM orders
WHERE user_id = $1 AND event_id = $2
`

type GetOrdersByUserAndEventParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
}

func (q *Queries) GetOrdersByUserAndEvent(ctx context.Context, arg GetOrdersByUserAndEventParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByUserAndEvent, arg.UserID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UserID,
			&i.OrderType,
			&i.Outcome,
			&i.Side,
			&i.Quantity,
			&i.Price,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderFill = `-- name: UpdateOrderFill :exec
UPDATE orders
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateOrderFillParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateOrderFill(ctx context.Context, arg UpdateOrderFillParams) error {
	_, err := q.db.Exec(ctx, updateOrderFill, arg.ID, arg.Status)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
