// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postion.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const decreasePosition = `-- name: DecreasePosition :execrows
UPDATE positions
SET
    shares = shares - $4,
    updated_at = NOW()
WHERE user_id = $1
  AND event_id = $2
  AND outcome = $3
  AND shares >= $4
`

type DecreasePositionParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
	Outcome string
	Shares  pgtype.Numeric
}

func (q *Queries) DecreasePosition(ctx context.Context, arg DecreasePositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, decreasePosition,
		arg.UserID,
		arg.EventID,
		arg.Outcome,
		arg.Shares,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPosition = `-- name: GetPosition :one
SELECT user_id, event_id, outcome, shares, avg_price, updated_at
FROM positions
WHERE user_id = $1
  AND event_id = $2
  AND outcome = $3
`

type GetPositionParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
	Outcome string
}

func (q *Queries) GetPosition(ctx context.Context, arg GetPositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, getPosition, arg.UserID, arg.EventID, arg.Outcome)
	var i Position
	err := row.Scan(
		&i.UserID,
		&i.EventID,
		&i.Outcome,
		&i.Shares,
		&i.AvgPrice,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPosition = `-- name: UpsertPosition :exec
INSERT INTO positions (
    user_id,
    event_id,
    outcome,
    shares,
    avg_price
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, event_id, outcome)
DO UPDATE SET
    shares = positions.shares + EXCLUDED.shares,
    avg_price = EXCLUDED.avg_price,
    updated_at = NOW()
`

type UpsertPositionParams struct {
	UserID   uuid.UUID
	EventID  uuid.UUID
	Outcome  string
	Shares   pgtype.Numeric
	AvgPrice pgtype.Numeric
}

func (q *Queries) UpsertPosition(ctx context.Context, arg UpsertPositionParams) error {
	_, err := q.db.Exec(ctx, upsertPosition,
		arg.UserID,
		arg.EventID,
		arg.Outcome,
		arg.Shares,
		arg.AvgPrice,
	)
	return err
}
