// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trades.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getTradesByEvent = `-- name: GetTradesByEvent :many
SELECT id, event_id, outcome, taker_order_id, maker_order_id, buyer_id, seller_id, taker_side, quantity, price, created_at
FROM trades
WHERE event_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTradesByEventParams struct {
	EventID uuid.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) GetTradesByEvent(ctx context.Context, arg GetTradesByEventParams) ([]Trade, error) {
	rows, err := q.db.Query(ctx, getTradesByEvent, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Outcome,
			&i.TakerOrderID,
			&i.MakerOrderID,
			&i.BuyerID,
			&i.SellerID,
			&i.TakerSide,
			&i.Quantity,
			&i.Price,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTrade = `-- name: InsertTrade :one
INSERT INTO trades (
    id,
    event_id,
    outcome,
    taker_order_id,
    maker_order_id,
    buyer_id,
    seller_id,
    taker_side,
    quantity,
    price
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, event_id, outcome, taker_order_id, maker_order_id, buyer_id, seller_id, taker_side, quantity, price, created_at
`

type InsertTradeParams struct {
	ID           uuid.UUID
	EventID      uuid.UUID
	Outcome      string
	TakerOrderID uuid.UUID
	MakerOrderID uuid.UUID
	BuyerID      uuid.UUID
	SellerID     uuid.UUID
	TakerSide    string
	Quantity     pgtype.Numeric
	Price        pgtype.Numeric
}

func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) (Trade, error) {
	row := q.db.QueryRow(ctx, insertTrade,
		arg.ID,
		arg.EventID,
		arg.Outcome,
		arg.TakerOrderID,
		arg.MakerOrderID,
		arg.BuyerID,
		arg.SellerID,
		arg.TakerSide,
		arg.Quantity,
		arg.Price,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Outcome,
		&i.TakerOrderID,
		&i.MakerOrderID,
		&i.BuyerID,
		&i.SellerID,
		&i.TakerSide,
		&i.Quantity,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}
