// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (
    user_id,
    order_id,
    trade_id,
    type,
    quantity,
    price,
    amount,
    outcome
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, order_id, trade_id, type, quantity, price, amount, outcome, created_at
`

type InsertTransactionParams struct {
	UserID   uuid.UUID
	OrderID  pgtype.UUID
	TradeID  pgtype.UUID
	Type     string
	Quantity pgtype.Numeric
	Price    pgtype.Numeric
	Amount   pgtype.Numeric
	Outcome  pgtype.Text
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.UserID,
		arg.OrderID,
		arg.TradeID,
		arg.Type,
		arg.Quantity,
		arg.Price,
		arg.Amount,
		arg.Outcome,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderID,
		&i.TradeID,
		&i.Type,
		&i.Quantity,
		&i.Price,
		&i.Amount,
		&i.Outcome,
		&i.CreatedAt,
	)
	return i, err
}
